import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { useAccount, useConnectors, useStarknetExecute } from '@starknet-react/core'
import { getCalls } from './generator'

export default function Home() {

  const { address } = useAccount()
  const { available, connect } = useConnectors();
  const { execute } = useStarknetExecute({ calls: getCalls() });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {address ? "gm " + address.slice(0, 5) : "plz connect"}
        </h1>

        <div className={styles.grid}>

          <div onClick={() => connect(available[0])} className={styles.card}>
            Connect
          </div>

          <div onClick={execute} className={styles.card}>
            Premint
          </div>

        </div>

      </main>
    </div>
  )
}
